// Compiles src/shared/theme.css with Tailwind, then wraps the result in a
// TypeScript module so the components can ship it inside their shadow root
// as a <style> tag (works regardless of how the bundler treats .css files).
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const outCss = path.join(root, 'node_modules/.cache/ruxlo-tailwind.css');
mkdirSync(path.dirname(outCss), { recursive: true });

execFileSync(
  'npx',
  ['@tailwindcss/cli', '-i', 'src/shared/theme.css', '-o', outCss, '--minify'],
  { cwd: root, stdio: 'inherit' }
);

const css = readFileSync(outCss, 'utf8').trim();
const outTs = path.join(root, 'src/shared/generated/tailwind-css.ts');
mkdirSync(path.dirname(outTs), { recursive: true });
writeFileSync(
  outTs,
  `// GENERATED by scripts/build-css.mjs — do not edit. Run \`npm run css\`.\nexport const TAILWIND_CSS: string = ${JSON.stringify(css)};\n`
);
console.log(`wrote ${path.relative(root, outTs)} (${(css.length / 1024).toFixed(1)} KB)`);
